version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    container_name: chaibackend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
