apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaibackend-deployment
  labels:
    app: chaibackend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chaibackend
  template:
    metadata:
      labels:
        app: chaibackend
    spec:
      containers:
        - name: chaibackend
          image: chaibackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chaibackend-service
spec:
  selector:
    app: chaibackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
