services:
  - type: web
    name: chaibackend
    env: node
    plan: starter
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
